### ISSUE TITLE
Pillow

### ISSUE THREAD

**Issue by neko2h** [sleepyb285/fish#1]
Где pillow в r.txt?

**Comment by sleepyb285** [comment]
![image](https://user-images.githubusercontent.com/116361513/200751011-0eeb72fc-52ba-4965-a87b-f1a55f6ede8e.png)
Записать его туда руками?

**Comment by neko2h** [comment]
Pip freeze гугли

**Comment by neko2h** [comment]
Суть в том что когда ты запускаешь проект в докере или на другой машине ты устанавливаешь пакеты необходимые для запуска из этого файла
