### ISSUE TITLE
Slug

### ISSUE THREAD

**Issue by neko2h** [sleepyb285/fish#3]
У тебя слаг не рабочий. В изначальном варианте он не работает с кириллицей, такие дела.

**Comment by sleepyb285** [comment]
В каком плане? В админке я его вижу на латинице, или я что-то не так понимаю?
![image](https://user-images.githubusercontent.com/116361513/200751600-8dc57001-07d4-4385-b76b-ffd7073c3f01.png)

**Comment by neko2h** [comment]
Прикольно,  у меня отказывался, хех. Надо зачекать
